# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-15 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='duration',
            field=models.CharField(choices=[('Single Day', 'Single Day'), ('Multiple Day', 'Multiple Day'), ('Half Day', 'Half Day')], default='Single Day', max_length=20),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('Casual Leave', 'Casual Leave'), ('Sick Leave', 'Sick Leave')], default='Casual Leave', max_length=20),
        ),
    ]
