# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-15 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200615_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='total_leaves',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Stat Date'),
        ),
    ]
