# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-15 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200615_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='total_leaves',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, related_name='leave_count', to='app.Leave'),
        ),
    ]
