# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-16 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_employeedetails_total_leaves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='start_date',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
