# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-17 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200616_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='total_leaves',
        ),
    ]
