# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-17 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_employeedetails_total_leaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='total_no_of_leaves',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
