# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-17 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200617_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='no_of_days',
        ),
    ]
