# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-17 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_leaveapplication_no_of_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='duration',
            field=models.CharField(choices=[('FULL Day', 'Full Day'), ('Half Day', 'Half Day')], default='Full Day', max_length=20),
        ),
    ]
