# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-19 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200617_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='no_of_remaining_leaves',
            field=models.PositiveIntegerField(default=18),
        ),
    ]
