# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2020-06-19 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200619_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='no_of_leaves',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='no_of_remaining_leaves',
            field=models.FloatField(default=18),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='total_no_of_leaves',
            field=models.FloatField(default=18),
        ),
    ]
